name: Build and Update Release Branch

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main
    
    - name: Set up Node.js (if you're using Node.js for your build process)
      uses: actions/setup-node@v2
      with:
        node-version: '16.x' 

    - name: Install dependencies
      run: npm install 

    - name: Build release files
      run: npm run build

    - name: Checkout release branch
      run: |
        git fetch origin
        git switch --create release origin/release || git switch release
    
    - name: Clear existing files on the release branch
      run: |
        git rm -rf .
        git clean -fdx
    
    # - name: Copy release files
    #   run: cp -r dist/* . # Adjust the source and destination as needed

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update release files"
        git push origin release --force
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
